@ECHO OFF

REM ================
REM CONVENTIONS
REM ================
REM -   All "*FOLDER_PATH" variables must not have a trailing backslash (a folder/directory separator).
REM     This is different compared to the convention used for MSBuild folder/directory properties.
REM -   All "*FOLDER_PATH" variables defined below are base/root folder/directory paths,
REM     even though their variable names don't use "BASE" word.


SET BUILD_CONFIGURATION_FOLDER_NAME=build
SET SOURCE_CODE_FOLDER_NAME=src
SET ARTIFACTS_FOLDER_NAME=artifacts
SET ARTIFACTS_OUTPUT_FOLDER_NAME=bin
SET ARTIFACTS_PACKAGES_FOLDER_NAME=packages
SET ARTIFACTS_TEST_RESULTS_FOLDER_NAME=testresults

SET WORKSPACE_FOLDER_PATH=%~dp0
SET WORKSPACE_FOLDER_PATH=%WORKSPACE_FOLDER_PATH:~0,-1%
SET BUILD_CONFIGURATION_FOLDER_PATH=%WORKSPACE_FOLDER_PATH%\%BUILD_CONFIGURATION_FOLDER_NAME%
SET SOURCE_CODE_FOLDER_PATH=%WORKSPACE_FOLDER_PATH%\%SOURCE_CODE_FOLDER_NAME%
SET ARTIFACTS_FOLDER_PATH=%WORKSPACE_FOLDER_PATH%\%ARTIFACTS_FOLDER_NAME%
SET ARTIFACTS_OUTPUT_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_OUTPUT_FOLDER_NAME%
SET ARTIFACTS_PACKAGES_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_PACKAGES_FOLDER_NAME%
SET ARTIFACTS_TEST_RESULTS_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_TEST_RESULTS_FOLDER_NAME%


SET PARAMETER___RUN_BUILD___DEFAULT=true
SET PARAMETER___RUN_TEST___DEFAULT=true
SET BUILD_PARAMETER___VERSION___DEFAULT=4.0.0
SET BUILD_PARAMETER___CONFIGURATION___DEFAULT=Release
SET BUILD_PARAMETER___ENABLE_SOURCE_LINK___DEFAULT=true
SET TEST_PARAMETER___TARGET_FRAMEWORKS___DEFAULT=net8.0;net7.0;net6.0;net48


SET BUILD_PARAMETERS=^
    "NHibernate.ObservableCollections-All.sln"


SET PACKAGE_PARAMETERS=^
    "NHibernate.ObservableCollections."


SET TEST_PARAMETERS=^
    "NHibernate.ObservableCollections.Tests|%TEST_PARAMETER___TARGET_FRAMEWORKS_DEFAULT%"
