@ECHO OFF


SET BUILD_CONFIGURATION_FOLDER_NAME=build
SET SOURCE_CODE_FOLDER_NAME=src
SET ARTIFACTS_FOLDER_NAME=artifacts
SET ARTIFACTS_OUTPUT_FOLDER_NAME=bin
SET ARTIFACTS_PACKAGES_FOLDER_NAME=packages
SET ARTIFACTS_TEST_RESULTS_FOLDER_NAME=testresults

SET BUILD_CONFIGURATION_FOLDER_PATH=%BUILD_CONFIGURATION_FOLDER_NAME%
SET SOURCE_CODE_FOLDER_PATH=%SOURCE_CODE_FOLDER_NAME%
SET ARTIFACTS_FOLDER_PATH=%ARTIFACTS_FOLDER_NAME%
SET ARTIFACTS_OUTPUT_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_OUTPUT_FOLDER_NAME%
SET ARTIFACTS_PACKAGES_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_PACKAGES_FOLDER_NAME%
SET ARTIFACTS_TEST_RESULTS_FOLDER_PATH=%ARTIFACTS_FOLDER_PATH%\%ARTIFACTS_TEST_RESULTS_FOLDER_NAME%


SET BUILD_PARAMETER___VERSION_DEFAULT=5.0.0
SET BUILD_PARAMETER___CONFIGURATION_DEFAULT=Release

SET BUILD_PARAMETERS=^
    "NHibernate.ObservableCollections-All.sln|%BUILD_PARAMETER___VERSION_DEFAULT%|%BUILD_PARAMETER___CONFIGURATION_DEFAULT%"


SET TEST_PARAMETER___TARGET_FRAMEWORKS_DEFAULT=net9.0;net8.0;net48

SET TEST_PARAMETERS=^
    "NHibernate.ObservableCollections.Tests|%TEST_PARAMETER___TARGET_FRAMEWORKS_DEFAULT%"
