//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iesi.Collections.Generic.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iesi.Collections.Generic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deferred event notifications have already been completed..
        /// </summary>
        public static string ObservableCollection_DeferredEventNotificationsCompleted {
            get {
                return ResourceManager.GetString("ObservableCollection_DeferredEventNotificationsCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event notifications are already being deferred for this &apos;ObservableCollection&apos;. Nested deferred event notification operations are not allowed..
        /// </summary>
        public static string ObservableCollection_NestedDeferredEventNotificationNotAllowed {
            get {
                return ResourceManager.GetString("ObservableCollection_NestedDeferredEventNotificationNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot change &apos;ObservableCollection&apos; during a &apos;CollectionChanged&apos; event..
        /// </summary>
        public static string ObservableCollection_ReentrancyNotAllowed {
            get {
                return ResourceManager.GetString("ObservableCollection_ReentrancyNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deferred event notifications have already been completed..
        /// </summary>
        public static string ObservableSet_DeferredEventNotificationsCompleted {
            get {
                return ResourceManager.GetString("ObservableSet_DeferredEventNotificationsCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination array &apos;{0}&apos; is too small..
        /// </summary>
        public static string ObservableSet_DestinationArrayTooSmall {
            get {
                return ResourceManager.GetString("ObservableSet_DestinationArrayTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The internal storage of &apos;ObservableSet&apos; is inconsistent. &apos;{0}&apos; is {1}, but &apos;{2}&apos; is {3}..
        /// </summary>
        public static string ObservableSet_InternalStorageInconsistent {
            get {
                return ResourceManager.GetString("ObservableSet_InternalStorageInconsistent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event notifications are already being deferred for this &apos;ObservableSet&apos;. Nested deferred event notification operations are not allowed..
        /// </summary>
        public static string ObservableSet_NestedDeferredEventNotificationsNotAllowed {
            get {
                return ResourceManager.GetString("ObservableSet_NestedDeferredEventNotificationsNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot change &apos;ObservableSet&apos; during a &apos;CollectionChanged&apos; event..
        /// </summary>
        public static string ObservableSet_ReentrancyNotAllowed {
            get {
                return ResourceManager.GetString("ObservableSet_ReentrancyNotAllowed", resourceCulture);
            }
        }
    }
}
