name: Build

on: [ push, pull_request ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_ROLL_FORWARD: Major

jobs:

  Build_Test_Package:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]

    env:
      TestResults_ArtifactName: TestResults_${{ matrix.configuration }}
      Packages_ArtifactName: Packages_${{ matrix.configuration }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Validate Build Infrastructure
        run: |
          & "$env:GITHUB_WORKSPACE\build\ValidateBuildInfrastructure.ps1"
        shell: pwsh

      - name: Prepare NuGet Local Package Sources
        run: |
          & "$env:GITHUB_WORKSPACE\build\PrepareNuGetLocalPackageSources.ps1" `
            -NuGetConfigFilePath "$env:GITHUB_WORKSPACE\nuget.config" `
            -PackageSourceKeyPrefix 'Local Package Artifacts'
        shell: pwsh

      - name: Build, Test, and Package
        run: |
          call "%GITHUB_WORKSPACE%\BuildPackages.cmd" --configuration "${{ matrix.configuration }}"
          if errorlevel 1 exit /b %errorlevel%
        shell: cmd

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          name: ${{ env.Packages_ArtifactName }}
          path: ${{ github.workspace }}\artifacts\packages\${{ matrix.configuration }}
          if-no-files-found: warn

      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          name: ${{ env.TestResults_ArtifactName }}
          path: ${{ github.workspace }}\artifacts\testresults\${{ matrix.configuration }}
          if-no-files-found: warn
