name: Build

on: [ push, pull_request ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_ROLL_FORWARD: Major

jobs:

  Framework_Validation:

    strategy:
      fail-fast: false
      matrix:
        framework: [net10.0, net9.0, net8.0, net48]
        configuration: [Release]

    runs-on: windows-latest

    env:
      TestResults_ArtifactName: TestResults_${{ matrix.framework }}_${{ matrix.configuration }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      - name: Setup Environment Variables
        run: |
          $WorkingDirectory = "$env:GITHUB_WORKSPACE"

          Write-Host "Working Directory: $WorkingDirectory"
          Write-Host "Framework: ${{ matrix.framework }}"
          Write-Host "Configuration: ${{ matrix.configuration }}"

          # Set the Azure DevOps default working directory env variable,
          # so tests only need to deal with a single env variable.
          "SYSTEM_DEFAULTWORKINGDIRECTORY=$WorkingDirectory" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Build and Test Framework
        run: |
          call "%GITHUB_WORKSPACE%\build\Build.Properties.cmd"
          call "%GITHUB_WORKSPACE%\build\BuildPackages.cmd" ^
            --configuration "${{ matrix.configuration }}" ^
            --frameworks "${{ matrix.framework }}" ^
            --no-package
        shell: cmd

      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ env.TestResults_ArtifactName }}
          path: ${{ github.workspace }}\artifacts\testresults\${{ matrix.configuration }}
          if-no-files-found: warn


  Package:

    needs: Framework_Validation

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]

    env:
      Packages_ArtifactName: Packages_${{ matrix.configuration }}
      TestResults_ArtifactName: TestResults_Package_${{ matrix.configuration }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      - name: Setup Environment Variables
        run: |
          $WorkingDirectory = "$env:GITHUB_WORKSPACE"

          Write-Host "Working Directory: $WorkingDirectory"
          Write-Host "Configuration: ${{ matrix.configuration }}"

          # Set the Azure DevOps default working directory env variable,
          # so tests only need to deal with a single env variable.
          "SYSTEM_DEFAULTWORKINGDIRECTORY=$WorkingDirectory" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Build and Package
        run: |
          call "%GITHUB_WORKSPACE%\build\Build.Properties.cmd"
          call "%GITHUB_WORKSPACE%\build\BuildPackages.cmd" ^
            --configuration "${{ matrix.configuration }}" ^
            --no-test
        shell: cmd

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ env.Packages_ArtifactName }}
          path: ${{ github.workspace }}\artifacts\packages\${{ matrix.configuration }}
          if-no-files-found: warn

      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ env.TestResults_ArtifactName }}
          path: ${{ github.workspace }}\artifacts\testresults\${{ matrix.configuration }}
          if-no-files-found: warn
